# fly.toml app configuration file generated for nameless-paper-6707 on 2023-08-14T12:22:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-sunset-9485"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
